### PR TITLE
Fixing NPE bug in KafkaOffsetCommitterListener

### LINKED ISSUE #9: NullPointerException is thrown in KafkaOffsetCommitterListener
When StreamingQuery is started but there are no new messages to process, [this](https://github.com/HeartSaVioR/spark-sql-kafka-offset-committer/blob/develop-spark3.0/src/main/scala/net/heartsavior/spark/KafkaOffsetCommitterListener.scala#L49) line throws a NullpointerException.

The reason is that lastExecution is null so exec will be Some(null).

The exception is thrown continuously until at least one message is processed.

### PR DESCRIPTION
**Pull request by szvasas**
Fixes #9

### CODE REVIEW

**Review by HeartSaVioR — APPROVED** [review]
LGTM. Thanks for the fix!

**Comment by szvasas** [comment]
Thank you for the quick review @HeartSaVioR!
Can we backport the commit to the develop-2.4 branch as well? Any chance that there is a new release coming out soon?

Thanks, I appreciate you creating this library!

**Comment by HeartSaVioR** [comment]
Yeah I ported back the change to develop-2.4 as well as released 0.4.0 for both Spark 3.0 and 2.4. It'd take around 2 days at most for maven repositories to catch up. Thanks again for the fix!

**Comment by HeartSaVioR** [comment]
And... the release is up!
https://search.maven.org/artifact/net.heartsavior.spark/spark-sql-kafka-offset-committer_2.11/0.4.0-spark-2.4/jar
https://search.maven.org/artifact/net.heartsavior.spark/spark-sql-kafka-offset-committer_2.12/0.4.0-spark-2.4/jar
https://search.maven.org/artifact/net.heartsavior.spark/spark-sql-kafka-offset-committer_2.12/0.4.0-spark-3.0/jar

**Pull request merged**
