### PR TITLE
Project migration to SBT to support cross build (Scala 2.11 and 2.12)

### PR DESCRIPTION
**Pull request by redsk**
Addresses #5 .

### CODE REVIEW

**Comment by redsk** [comment]
We need to run the checks in CircleCi.

**Comment by HeartSaVioR** [comment]
Closing and reopening to check CI setting.

**Comment by HeartSaVioR** [comment]
Shall we add version.sbt as well? To work with release plugin smoothly I had to move the version out of build.sbt in spark-state-tools project, and here build.sbt is also missing.

https://github.com/HeartSaVioR/spark-state-tools/blob/master/version.sbt

The version would be 0.2.0-SNAPSHOT.

Thanks!

**Comment by redsk** [comment]
Oh I missed that, sorry. I'll add it now.

**Comment by HeartSaVioR** [comment]
Superb! I'll manually test for the publish phase in local and merge this. Thanks!

**Comment by redsk** [comment]
You're more than welcome!

**Comment by HeartSaVioR** [comment]
I've tested and looks to be working. Thanks!

**Pull request merged**
